-- Game Day Operations: add suggestions and resolution tracking to swap_plan_impacts

-- Suggestions generated by the game day suggestion engine
ALTER TABLE swap_plan_impacts ADD COLUMN IF NOT EXISTS suggestions JSONB;

-- Resolution tracking
ALTER TABLE swap_plan_impacts ADD COLUMN IF NOT EXISTS resolution_type TEXT
  CHECK (resolution_type IN ('accepted_suggestion', 'manual_fix', 'no_action_needed', 'dismissed'));
ALTER TABLE swap_plan_impacts ADD COLUMN IF NOT EXISTS resolution_note TEXT;
ALTER TABLE swap_plan_impacts ADD COLUMN IF NOT EXISTS resolved_by TEXT;
ALTER TABLE swap_plan_impacts ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ;
