-- Seed fbo_handling_fees from fbo-fees.json
-- Regenerated 2026-03-21

INSERT INTO fbo_handling_fees (airport_code, fbo_name, chain, aircraft_type, facility_fee, gallons_to_waive, security_fee, landing_fee, overnight_fee, parking_info, source)
VALUES
  ('ABQ', 'Atlantic Aviation ABQ', 'Atlantic Aviation', 'Challenger 300', 1006, 404, 55, NULL, NULL, 'Complimentary (first hour) $30/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('ABQ', 'Atlantic Aviation ABQ', 'Atlantic Aviation', 'Citation X', 1063, 374, 55, NULL, NULL, 'Complimentary (first hour) $32/hr (next 11 hours) then $17/hr', 'jetinsight'),
  ('ACY', 'SIGNATURE ATLANTIC CITY', 'Signature Flight Support', 'Citation X', 1875.8, 520, 46, NULL, NULL, '', 'jetinsight'),
  ('ADS', 'Atlantic Aviation ADS', 'Atlantic Aviation', 'Challenger 300', 940, 404, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('ADS', 'Atlantic Aviation ADS', 'Atlantic Aviation', 'Citation X', 994, 374, 55, NULL, NULL, 'Complimentary (first hour) $27/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('AGC', 'Atlantic Aviation AGC', 'Atlantic Aviation', 'Challenger 300', 1180, 404, 55, NULL, NULL, 'Complimentary (first hour) $30/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('AGC', 'Atlantic Aviation AGC', 'Atlantic Aviation', 'Citation X', 1248, 374, 55, NULL, NULL, 'Complimentary (first hour) $32/hr (next 11 hours) then $17/hr', 'jetinsight'),
  ('ALB', 'Million Air ALB', 'Million Air', 'Challenger 300', 500, 400, 0, 201, 250, '', 'jetinsight'),
  ('ALB', 'Million Air ALB', 'Million Air', 'Citation X', 275, 200, 0, 215, 138, '', 'jetinsight'),
  ('AMA', 'SIGNATURE AMARILLO', 'Signature Flight Support', 'Challenger 300', 1140, 520, 26, NULL, NULL, '', 'jetinsight'),
  ('AMA', 'SIGNATURE AMARILLO', 'Signature Flight Support', 'Citation X', 1140, 520, 26, NULL, NULL, '', 'jetinsight'),
  ('ANC', 'Atlantic Aviation ANC', 'Atlantic Aviation', 'Challenger 300', 940, 404, 120, NULL, NULL, 'Complimentary (first hour) $47/hr (next 11 hours) then $26/hr', 'jetinsight'),
  ('ANC', 'Atlantic Aviation ANC', 'Atlantic Aviation', 'Citation X', 994, 374, 120, NULL, NULL, 'Complimentary (first hour) $50/hr (next 11 hours) then $27/hr', 'jetinsight'),
  ('ANC', 'SIGNATURE ANCHORAGE', 'Signature Flight Support', 'Challenger 300', 1300, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('ANC', 'SIGNATURE ANCHORAGE', 'Signature Flight Support', 'Citation X', 1300, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('ANE', 'Atlantic Aviation ANE', 'Atlantic Aviation', 'Challenger 300', 1115, 404, 55, NULL, NULL, 'Complimentary (first hour) $27/hr (next 11 hours) then $15/hr', 'jetinsight'),
  ('ANE', 'Atlantic Aviation ANE', 'Atlantic Aviation', 'Citation X', 1179, 374, 55, NULL, NULL, 'Complimentary (first hour) $29/hr (next 11 hours) then $15/hr', 'jetinsight'),
  ('ANU', 'SIGNATURE ANTIGUA', 'Signature Flight Support', 'Challenger 300', 2080, NULL, 70, NULL, NULL, '', 'jetinsight'),
  ('ANU', 'SIGNATURE ANTIGUA', 'Signature Flight Support', 'Citation X', 2080, NULL, 70, NULL, NULL, '', 'jetinsight'),
  ('APA', 'SIGNATURE DENVER CENTENNIAL - SOUTH', 'Signature Flight Support', 'Challenger 300', 1510, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('APA', 'SIGNATURE DENVER CENTENNIAL - NORTH', 'Signature Flight Support', 'Challenger 300', 1510, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('APA', 'SIGNATURE DENVER CENTENNIAL - SOUTH', 'Signature Flight Support', 'Citation X', 1510, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('APA', 'SIGNATURE DENVER CENTENNIAL - NORTH', 'Signature Flight Support', 'Citation X', 1510, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('APC', 'Atlantic Aviation APC', 'Atlantic Aviation', 'Challenger 300', 962, 404, 55, NULL, NULL, 'Complimentary (first hour) $24/hr (next 11 hours) then $13/hr', 'jetinsight'),
  ('APC', 'Atlantic Aviation APC', 'Atlantic Aviation', 'Citation X', 1017, 374, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('ASE', 'Atlantic Aviation ASE', 'Atlantic Aviation', 'Challenger 300', 1902, 404, 165, NULL, NULL, 'Complimentary (first hour) $102/hr (next 11 hours) then $55/hr', 'jetinsight'),
  ('ASE', 'Atlantic Aviation ASE', 'Atlantic Aviation', 'Citation X', 2011, 374, 165, NULL, NULL, 'Complimentary (first hour) $108/hr (next 11 hours) then $59/hr', 'jetinsight'),
  ('ATL', 'SIGNATURE ATLANTA', 'Signature Flight Support', 'Citation X', 1300, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('AUS', 'Atlantic Aviation AUS', 'Atlantic Aviation', 'Challenger 300', 874, 404, 55, NULL, NULL, 'Complimentary (first hour) $42/hr (next 11 hours) then $23/hr', 'jetinsight'),
  ('AUS', 'Atlantic Aviation AUS', 'Atlantic Aviation', 'Citation X', 925, 374, 55, NULL, NULL, 'Complimentary (first hour) $45/hr (next 11 hours) then $24/hr', 'jetinsight'),
  ('AUS', 'SIGNATURE AUSTIN', 'Signature Flight Support', 'Challenger 300', 1200, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('AUS', 'SIGNATURE AUSTIN', 'Signature Flight Support', 'Citation X', 1200, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('AVL', 'SIGNATURE ASHEVILLE', 'Signature Flight Support', 'Challenger 300', 1720, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('AVL', 'SIGNATURE ASHEVILLE', 'Signature Flight Support', 'Citation X', 1720, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('BAF', 'Atlantic Aviation BAF', 'Atlantic Aviation', 'Challenger 300', 1049, 404, 55, NULL, NULL, 'Complimentary (first hour) $24/hr (next 11 hours) then $13/hr', 'jetinsight'),
  ('BAF', 'Atlantic Aviation BAF', 'Atlantic Aviation', 'Citation X', 1110, 374, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('BCT', 'Atlantic Aviation BCT', 'Atlantic Aviation', 'Challenger 300', 1180, 404, 65, NULL, NULL, 'Complimentary (first hour) $250/hr (next 11 hours) then $134/hr', 'jetinsight'),
  ('BCT', 'Atlantic Aviation BCT', 'Atlantic Aviation', 'Citation X', 1248, 374, 65, NULL, NULL, 'Complimentary (first hour) $264/hr (next 11 hours) then $142/hr', 'jetinsight'),
  ('BCT', 'SIGNATURE BOCA RATON', 'Signature Flight Support', 'Challenger 300', NULL, NULL, 38, NULL, NULL, '', 'jetinsight'),
  ('BCT', 'SIGNATURE BOCA RATON', 'Signature Flight Support', 'Citation X', NULL, NULL, 38, NULL, NULL, '', 'jetinsight'),
  ('BDL', 'Atlantic Aviation BDL', 'Atlantic Aviation', 'Challenger 300', 1027, 404, 55, NULL, NULL, '{''unitPrice'': 0.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('BDL', 'Atlantic Aviation BDL', 'Atlantic Aviation', 'Citation X', 1086, 374, 55, NULL, NULL, '{''unitPrice'': 0.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('BDL', 'SIGNATURE HARTFORD', 'Signature Flight Support', 'Challenger 300', 1610, 520, 42, NULL, NULL, '', 'jetinsight'),
  ('BDL', 'SIGNATURE HARTFORD', 'Signature Flight Support', 'Citation X', 1610, 520, 42, NULL, NULL, '', 'jetinsight'),
  ('BDR', 'Atlantic Aviation BDR', 'Atlantic Aviation', 'Challenger 300', 940, 404, 55, NULL, NULL, 'Complimentary (first hour) $24/hr (next 11 hours) then $13/hr', 'jetinsight'),
  ('BDR', 'Atlantic Aviation BDR', 'Atlantic Aviation', 'Citation X', 994, 374, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('BED', 'Atlantic Aviation BED', 'Atlantic Aviation', 'Challenger 300', 1312, 404, 100, 132, 1453, 'Complimentary (first hour) $83/hr (next 11 hours) then $45/hr', 'jetinsight'),
  ('BED', 'Atlantic Aviation BED', 'Atlantic Aviation', 'Citation X', 1387, 374, 100, 119, 763, 'Complimentary (first hour) $87/hr (next 11 hours) then $47/hr', 'jetinsight'),
  ('BED', 'Boston, USA', 'Jet Aviation', 'Challenger 300', 1163, 450, 50, 132, 975, '', 'jetinsight'),
  ('BED', 'Boston, USA', 'Jet Aviation', 'Citation X', 1163, 450, 50, 119, 975, '', 'jetinsight'),
  ('BED', 'SIGNATURE BEDFORD', 'Signature Flight Support', 'Challenger 300', 1920, 520, 46, 132, 715, '', 'jetinsight'),
  ('BED', 'SIGNATURE BEDFORD', 'Signature Flight Support', 'Citation X', 1920, 520, 46, 119, 715, '', 'jetinsight'),
  ('BFI', 'SIGNATURE SEATTLE BOEING FIELD', 'Signature Flight Support', 'Citation X', 2340, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('BFL', 'Atlantic Aviation BFL', 'Atlantic Aviation', 'Challenger 300', 918, 404, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('BFL', 'Atlantic Aviation BFL', 'Atlantic Aviation', 'Citation X', 971, 374, 55, NULL, NULL, 'Complimentary (first hour) $27/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('BFM', 'SIGNATURE MOBILE DOWNTOWN', 'Signature Flight Support', 'Challenger 300', 1460, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('BFM', 'SIGNATURE MOBILE DOWNTOWN', 'Signature Flight Support', 'Citation X', 1460, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('BGI', 'SIGNATURE BARBADOS', 'Signature Flight Support', 'Challenger 300', 1460, NULL, NULL, NULL, NULL, '', 'jetinsight'),
  ('BGI', 'SIGNATURE BARBADOS', 'Signature Flight Support', 'Citation X', 1460, NULL, NULL, NULL, NULL, '', 'jetinsight'),
  ('BHM', 'Atlantic Aviation BHM', 'Atlantic Aviation', 'Challenger 300', 1137, 404, 55, NULL, NULL, 'Complimentary (first hour) $29/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('BHM', 'Atlantic Aviation BHM', 'Atlantic Aviation', 'Citation X', 1202, 374, 55, NULL, NULL, 'Complimentary (first hour) $30/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('BJC', 'SIGNATURE DENVER BROOMFIELD', 'Signature Flight Support', 'Citation X', 1510, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('BKL', 'SIGNATURE CLEVELAND', 'Signature Flight Support', 'Challenger 300', 1560, 520, 42, NULL, NULL, '', 'jetinsight'),
  ('BKL', 'SIGNATURE CLEVELAND', 'Signature Flight Support', 'Citation X', 1560, 520, 42, NULL, NULL, '', 'jetinsight'),
  ('BNA', 'Atlantic Aviation BNA', 'Atlantic Aviation', 'Challenger 300', 1027, 404, 55, NULL, NULL, 'Complimentary (first hour) $30/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('BNA', 'Atlantic Aviation BNA', 'Atlantic Aviation', 'Citation X', 1086, 374, 55, NULL, NULL, 'Complimentary (first hour) $32/hr (next 11 hours) then $17/hr', 'jetinsight'),
  ('BNA', 'SIGNATURE NASHVILLE', 'Signature Flight Support', 'Challenger 300', 1090, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('BNA', 'SIGNATURE NASHVILLE', 'Signature Flight Support', 'Citation X', 1090, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('BOS', 'SIGNATURE BOSTON', 'Signature Flight Support', 'Challenger 300', 3070, 520, 63, NULL, NULL, '', 'jetinsight'),
  ('BOS', 'SIGNATURE BOSTON', 'Signature Flight Support', 'Citation X', 3070, 520, 63, NULL, NULL, '', 'jetinsight'),
  ('BTR', 'SIGNATURE BATON ROUGE', 'Signature Flight Support', 'Citation X', 1140, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('BUF', 'SIGNATURE BUFFALO NIAGARA', 'Signature Flight Support', 'Challenger 300', 1560, 520, 27, NULL, NULL, '', 'jetinsight'),
  ('BUF', 'SIGNATURE BUFFALO NIAGARA', 'Signature Flight Support', 'Citation X', 1560, 520, 27, NULL, NULL, '', 'jetinsight'),
  ('BUR', 'Atlantic Aviation BUR', 'Atlantic Aviation', 'Challenger 300', 1137, 404, 55, NULL, NULL, 'Complimentary (first hour) $24/hr (next 11 hours) then $13/hr', 'jetinsight'),
  ('BUR', 'Atlantic Aviation BUR', 'Atlantic Aviation', 'Citation X', 1202, 374, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('BWI', 'SIGNATURE BALTIMORE', 'Signature Flight Support', 'Challenger 300', 2240, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('BWI', 'SIGNATURE BALTIMORE', 'Signature Flight Support', 'Citation X', 2240, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('BZN', 'Bozeman, USA', 'Jet Aviation', 'Challenger 300', 625, 250, 50, 101, 127, '', 'jetinsight'),
  ('BZN', 'Bozeman, USA', 'Jet Aviation', 'Citation X', 625, 250, 50, 108, 127, '', 'jetinsight'),
  ('BZN', 'Million Air BZN', 'Million Air', 'Challenger 300', 350, 400, 0, 101, 350, '$350, 1 night / 0 gals', 'jetinsight'),
  ('BZN', 'Million Air BZN', 'Million Air', 'Citation X', 350, 400, 0, 108, 350, '$350, 1 night / 0 gals', 'jetinsight'),
  ('BZN', 'SIGNATURE BOZEMAN YELLOWSTONE', 'Signature Flight Support', 'Challenger 300', 1980, 520, 38, 101, 10, '', 'jetinsight'),
  ('BZN', 'SIGNATURE BOZEMAN YELLOWSTONE', 'Signature Flight Support', 'Citation X', 1980, 520, 38, 108, 10, '', 'jetinsight'),
  ('CHO', 'SIGNATURE CHARLOTTESVILLE', 'Signature Flight Support', 'Citation X', 1820, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('CHS', 'Atlantic Aviation CHS', 'Atlantic Aviation', 'Challenger 300', 1180, 404, 55, NULL, NULL, 'Complimentary (first hour) $34/hr (next 11 hours) then $18/hr', 'jetinsight'),
  ('CHS', 'Atlantic Aviation CHS', 'Atlantic Aviation', 'Citation X', 1248, 374, 55, NULL, NULL, 'Complimentary (first hour) $36/hr (next 11 hours) then $19/hr', 'jetinsight'),
  ('CHS', 'SIGNATURE CHARLESTON', 'Signature Flight Support', 'Challenger 300', 1510, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('CHS', 'SIGNATURE CHARLESTON', 'Signature Flight Support', 'Citation X', 1510, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('CID', 'SIGNATURE CEDAR RAPIDS', 'Signature Flight Support', 'Citation X', 1660, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('CLE', 'Atlantic Aviation CLE', 'Atlantic Aviation', 'Challenger 300', 1071, 404, 55, NULL, NULL, 'Complimentary (first hour) $27/hr (next 11 hours) then $15/hr', 'jetinsight'),
  ('CLE', 'Atlantic Aviation CLE', 'Atlantic Aviation', 'Citation X', 1133, 374, 55, NULL, NULL, 'Complimentary (first hour) $29/hr (next 11 hours) then $15/hr', 'jetinsight'),
  ('CMH', 'SIGNATURE COLUMBUS', 'Signature Flight Support', 'Challenger 300', 1510, 520, 46, NULL, NULL, '', 'jetinsight'),
  ('CMH', 'SIGNATURE COLUMBUS', 'Signature Flight Support', 'Citation X', 1510, 520, 46, NULL, NULL, '', 'jetinsight'),
  ('CPR', 'Atlantic Aviation CPR', 'Atlantic Aviation', 'Challenger 300', 962, 404, 55, NULL, NULL, '{''unitPrice'': 372.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('CPR', 'Atlantic Aviation CPR', 'Atlantic Aviation', 'Citation X', 1017, 374, 55, NULL, NULL, '{''unitPrice'': 393.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('CRP', 'Atlantic Aviation CRP', 'Atlantic Aviation', 'Challenger 300', 1093, 404, 65, NULL, NULL, '{''unitPrice'': 415.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('CRP', 'Atlantic Aviation CRP', 'Atlantic Aviation', 'Citation X', 1156, 374, 65, NULL, NULL, '{''unitPrice'': 439.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('CRQ', 'Atlantic Aviation CRQ', 'Atlantic Aviation', 'Challenger 300', 1137, 404, 65, NULL, NULL, 'Complimentary (first hour) $27/hr (next 11 hours) then $15/hr', 'jetinsight'),
  ('CRQ', 'Atlantic Aviation CRQ', 'Atlantic Aviation', 'Citation X', 1202, 374, 65, NULL, NULL, 'Complimentary (first hour) $29/hr (next 11 hours) then $15/hr', 'jetinsight'),
  ('DAL', 'Atlantic Aviation DAL', 'Atlantic Aviation', 'Challenger 300', 1071, 404, 55, 255, 590, 'Complimentary (first hour) $34/hr (next 11 hours) then $18/hr', 'jetinsight'),
  ('DAL', 'Atlantic Aviation DAL', 'Atlantic Aviation', 'Citation X', 1133, 374, 55, 273, 624, 'Complimentary (first hour) $36/hr (next 11 hours) then $19/hr', 'jetinsight'),
  ('DAL', 'Business Jet Center DAL', 'Business Jet Center', 'Challenger 300', 640, 375, 40, 255, 435, '', 'jetinsight'),
  ('DAL', 'Business Jet Center DAL', 'Business Jet Center', 'Citation X', 640, 375, 40, 273, 435, '', 'jetinsight'),
  ('DAL', 'Dallas, USA', 'Jet Aviation', 'Challenger 300', 750, 450, 25, 255, 241, '', 'jetinsight'),
  ('DAL', 'Dallas, USA', 'Jet Aviation', 'Citation X', 750, 450, 25, 273, 241, '', 'jetinsight'),
  ('DAL', 'SIGNATURE DALLAS - TERMINAL 1', 'Signature Flight Support', 'Challenger 300', 1350, 520, 43, 255, 680, '', 'jetinsight'),
  ('DAL', 'SIGNATURE DALLAS - TERMINAL 2', 'Signature Flight Support', 'Challenger 300', 1350, 520, 43, 255, 680, '', 'jetinsight'),
  ('DAL', 'SIGNATURE DALLAS - TERMINAL 3', 'Signature Flight Support', 'Challenger 300', 1155, 370, 40, 255, 667, '', 'jetinsight'),
  ('DAL', 'SIGNATURE DALLAS - TERMINAL 4', 'Signature Flight Support', 'Challenger 300', 1350, 520, 43, 255, 680, '', 'jetinsight'),
  ('DAL', 'SIGNATURE DALLAS - TERMINAL 1', 'Signature Flight Support', 'Citation X', 1350, 520, 43, 273, 680, '', 'jetinsight'),
  ('DAL', 'SIGNATURE DALLAS - TERMINAL 2', 'Signature Flight Support', 'Citation X', 1350, 520, 43, 273, 680, '', 'jetinsight'),
  ('DAL', 'SIGNATURE DALLAS - TERMINAL 3', 'Signature Flight Support', 'Citation X', 1155, 370, 30, 273, 667, '', 'jetinsight'),
  ('DAL', 'SIGNATURE DALLAS - TERMINAL 4', 'Signature Flight Support', 'Citation X', 1350, 520, 43, 273, 680, '', 'jetinsight'),
  ('DCA', 'SIGNATURE WASHINGTON DC', 'Signature Flight Support', 'Challenger 300', 2340, 520, 55, NULL, NULL, '', 'jetinsight'),
  ('DCA', 'SIGNATURE WASHINGTON DC', 'Signature Flight Support', 'Citation X', 2340, 520, 55, NULL, NULL, '', 'jetinsight'),
  ('DEN', 'SIGNATURE DENVER', 'Signature Flight Support', 'Challenger 300', 2390, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('DEN', 'SIGNATURE DENVER', 'Signature Flight Support', 'Citation X', 2390, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('DSM', 'SIGNATURE DES MOINES', 'Signature Flight Support', 'Challenger 300', 1660, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('DSM', 'SIGNATURE DES MOINES', 'Signature Flight Support', 'Citation X', 1660, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('DTS', 'Atlantic Aviation DTS', 'Atlantic Aviation', 'Challenger 300', 1115, 404, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('DTS', 'Atlantic Aviation DTS', 'Atlantic Aviation', 'Citation X', 1179, 374, 55, NULL, NULL, 'Complimentary (first hour) $27/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('DTW', 'SIGNATURE DETROIT METROPOLITAN', 'Signature Flight Support', 'Challenger 300', 1669.2, 520, 40.66, NULL, NULL, '', 'jetinsight'),
  ('DTW', 'SIGNATURE DETROIT METROPOLITAN', 'Signature Flight Support', 'Citation X', 1669.2, 520, 40.66, NULL, NULL, '', 'jetinsight'),
  ('EFD', 'SIGNATURE HOUSTON', 'Signature Flight Support', 'Citation X', 830, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('EIS', 'SIGNATURE TORTOLA', 'Signature Flight Support', 'Challenger 300', 1660, NULL, 425, NULL, NULL, '', 'jetinsight'),
  ('EIS', 'SIGNATURE TORTOLA', 'Signature Flight Support', 'Citation X', 1660, NULL, 425, NULL, NULL, '', 'jetinsight'),
  ('ELM', 'Atlantic Aviation ELM', 'Atlantic Aviation', 'Challenger 300', 962, 404, 55, NULL, NULL, '{''unitPrice'': 372.0, ''comment'': ''Overnight Parking''}', 'jetinsight'),
  ('ELM', 'Atlantic Aviation ELM', 'Atlantic Aviation', 'Citation X', 1017, 374, 55, NULL, NULL, '{''unitPrice'': 393.0, ''comment'': ''Overnight Parking''}', 'jetinsight'),
  ('ELP', 'Atlantic Aviation ELP', 'Atlantic Aviation', 'Challenger 300', 918, 404, 55, NULL, NULL, 'Complimentary (first hour) $24/hr (next 11 hours) then $13/hr', 'jetinsight'),
  ('ELP', 'Atlantic Aviation ELP', 'Atlantic Aviation', 'Citation X', 971, 374, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('EUG', 'Atlantic Aviation EUG', 'Atlantic Aviation', 'Challenger 300', 1071, 404, NULL, NULL, NULL, '{''unitPrice'': 0.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('EUG', 'Atlantic Aviation EUG', 'Atlantic Aviation', 'Citation X', 1133, 374, NULL, NULL, NULL, '{''unitPrice'': 0.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('EWR', 'SIGNATURE NEWARK', 'Signature Flight Support', 'Challenger 300', 2987.5, 520, 52, NULL, NULL, '', 'jetinsight'),
  ('EWR', 'SIGNATURE NEWARK', 'Signature Flight Support', 'Citation X', 2987.5, 520, 52, NULL, NULL, '', 'jetinsight'),
  ('EYW', 'SIGNATURE KEY WEST', 'Signature Flight Support', 'Citation X', 1140, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('F45', 'SIGNATURE NORTH PALM BEACH COUNTY', 'Signature Flight Support', 'Citation X', 1400, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('FAI', 'Atlantic Aviation FAI', 'Atlantic Aviation', 'Challenger 300', 1049, 404, 55, NULL, NULL, '{''unitPrice'': 372.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('FAI', 'Atlantic Aviation FAI', 'Atlantic Aviation', 'Citation X', 1110, 374, 55, NULL, NULL, '{''unitPrice'': 393.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('FAT', 'Atlantic Aviation FAT', 'Atlantic Aviation', 'Challenger 300', 1224, 404, 55, NULL, NULL, 'Complimentary (first hour) $24/hr (next 11 hours) then $13/hr', 'jetinsight'),
  ('FAT', 'Atlantic Aviation FAT', 'Atlantic Aviation', 'Citation X', 1295, 374, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('FAT', 'SIGNATURE FRESNO YOSEMITE', 'Signature Flight Support', 'Challenger 300', 1560, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('FAT', 'SIGNATURE FRESNO YOSEMITE', 'Signature Flight Support', 'Citation X', 1560, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('FAY', 'SIGNATURE FAYETTEVILLE', 'Signature Flight Support', 'Citation X', 1230, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('FDK', 'SIGNATURE FREDERICK', 'Signature Flight Support', 'Challenger 300', 1200, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('FDK', 'SIGNATURE FREDERICK', 'Signature Flight Support', 'Citation X', 1200, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('FLL', 'SIGNATURE FORT LAUDERDALE HOLLYWOOD', 'Signature Flight Support', 'Challenger 300', 1350, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('FLL', 'SIGNATURE FORT LAUDERDALE HOLLYWOOD', 'Signature Flight Support', 'Citation X', 1350, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('FMN', 'Atlantic Aviation FMN', 'Atlantic Aviation', 'Challenger 300', 1049, 404, 55, NULL, NULL, 'Complimentary (first hour) $27/hr (next 11 hours) then $15/hr', 'jetinsight'),
  ('FMN', 'Atlantic Aviation FMN', 'Atlantic Aviation', 'Citation X', 1110, 374, 55, NULL, NULL, 'Complimentary (first hour) $29/hr (next 11 hours) then $15/hr', 'jetinsight'),
  ('FOK', 'Modern Aviation Westhampton Beach', 'Modern Aviation', 'Challenger 300', 1300, 450, 100, 252, 438, '', 'jetinsight'),
  ('FOK', 'Modern Aviation Westhampton Beach', 'Modern Aviation', 'Citation X', 1300, 450, 100, 252, 461, '', 'jetinsight'),
  ('FOK', 'SIGNATURE WESTHAMPTON', 'Signature Flight Support', 'Challenger 300', 1638, 520, NULL, 252, 960, '', 'jetinsight'),
  ('FOK', 'SIGNATURE WESTHAMPTON', 'Signature Flight Support', 'Citation X', 1638, 520, NULL, 252, 960, '', 'jetinsight'),
  ('FRG', 'Atlantic Aviation FRG', 'Atlantic Aviation', 'Challenger 300', 940, 404, 55, NULL, NULL, '{''unitPrice'': 372.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('FRG', 'Atlantic Aviation FRG', 'Atlantic Aviation', 'Citation X', 994, 374, 55, NULL, NULL, '{''unitPrice'': 393.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('FSD', 'SIGNATURE SIOUX FALLS', 'Signature Flight Support', 'Challenger 300', 1550.52, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('FSD', 'SIGNATURE SIOUX FALLS', 'Signature Flight Support', 'Citation X', 1550.52, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('FSM', 'SIGNATURE FORT SMITH', 'Signature Flight Support', 'Challenger 300', 940, 520, 26, NULL, NULL, '', 'jetinsight'),
  ('FSM', 'SIGNATURE FORT SMITH', 'Signature Flight Support', 'Citation X', 940, 520, 26, NULL, NULL, '', 'jetinsight'),
  ('FTW', 'Modern Aviation Fort Worth', 'Modern Aviation', 'Challenger 300', 700, 415, 60, 0, 394, '', 'jetinsight'),
  ('FTW', 'Modern Aviation Fort Worth', 'Modern Aviation', 'Citation X', 700, 415, 60, 200, 415, '', 'jetinsight'),
  ('FTW', 'Texas Jet FTW', 'Texas Jet', 'Challenger 300', 0, NULL, 0, 0, 120, '$120, 1 night / 400 gals', 'jetinsight'),
  ('FTW', 'Texas Jet FTW', 'Texas Jet', 'Citation X', 0, NULL, 0, 200, 150, '$150, 1 night / 400 gals', 'jetinsight'),
  ('FTY', 'SIGNATURE ATLANTA FULTON COUNTY', 'Signature Flight Support', 'Challenger 300', 940, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('FTY', 'SIGNATURE ATLANTA FULTON COUNTY', 'Signature Flight Support', 'Citation X', 940, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('FXE', 'Atlantic Aviation FXE', 'Atlantic Aviation', 'Challenger 300', 1006, 404, 55, NULL, NULL, '{''unitPrice'': 481.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('FXE', 'Atlantic Aviation FXE', 'Atlantic Aviation', 'Citation X', 1063, 374, 55, NULL, NULL, '{''unitPrice'': 509.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('FXE', 'SIGNATURE FORT LAUDERDALE EXECUTIVE', 'Signature Flight Support', 'Challenger 300', 730, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('FXE', 'SIGNATURE FORT LAUDERDALE EXECUTIVE', 'Signature Flight Support', 'Citation X', 730, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('GCM', 'Atlantic Aviation GCM', 'Atlantic Aviation', 'Challenger 300', 1552, 404, 55, NULL, NULL, '{''unitPrice'': 0.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('GCM', 'Atlantic Aviation GCM', 'Atlantic Aviation', 'Citation X', 1641, 374, 55, NULL, NULL, '{''unitPrice'': 0.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('GEG', 'SIGNATURE SPOKANE', 'Signature Flight Support', 'Citation X', 1400, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('GND', 'SIGNATURE GRENADA', 'Signature Flight Support', 'Challenger 300', 1510, NULL, 375, NULL, NULL, '', 'jetinsight'),
  ('GND', 'SIGNATURE GRENADA', 'Signature Flight Support', 'Citation X', 1510, NULL, 375, NULL, NULL, '', 'jetinsight'),
  ('GPI', 'Atlantic Aviation GPI', 'Atlantic Aviation', 'Challenger 300', 1093, 404, 40, NULL, NULL, '{''unitPrice'': 525.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('GPI', 'Atlantic Aviation GPI', 'Atlantic Aviation', 'Citation X', 1156, 374, 40, NULL, NULL, '{''unitPrice'': 555.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('GRR', 'SIGNATURE GRAND RAPIDS', 'Signature Flight Support', 'Citation X', 1560, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('GSO', 'SIGNATURE GREENSBORO', 'Signature Flight Support', 'Challenger 300', 1400, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('GSO', 'SIGNATURE GREENSBORO', 'Signature Flight Support', 'Citation X', 1400, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('HDN', 'Atlantic Aviation HDN', 'Atlantic Aviation', 'Challenger 300', 1159, 404, 55, NULL, NULL, 'Complimentary (first hour) $32/hr (next 11 hours) then $17/hr', 'jetinsight'),
  ('HDN', 'Atlantic Aviation HDN', 'Atlantic Aviation', 'Citation X', 1225, 374, 55, NULL, NULL, 'Complimentary (first hour) $34/hr (next 11 hours) then $18/hr', 'jetinsight'),
  ('HNL', 'Atlantic Aviation HNL', 'Atlantic Aviation', 'Challenger 300', NULL, 404, 55, NULL, NULL, 'Complimentary (first hour) $42/hr (next 11 hours) then $23/hr', 'jetinsight'),
  ('HNL', 'Atlantic Aviation HNL', 'Atlantic Aviation', 'Citation X', NULL, 374, 55, NULL, NULL, 'Complimentary (first hour) $45/hr (next 11 hours) then $24/hr', 'jetinsight'),
  ('HNL', 'SIGNATURE HONOLULU', 'Signature Flight Support', 'Challenger 300', 1361.26, NULL, 36, NULL, NULL, '', 'jetinsight'),
  ('HNL', 'SIGNATURE HONOLULU', 'Signature Flight Support', 'Citation X', 1361.26, NULL, 36, NULL, NULL, '', 'jetinsight'),
  ('HOU', 'Atlantic Aviation HOU', 'Atlantic Aviation', 'Challenger 300', 874, 404, 55, 85, 420, '$420, 0 night / 0% waived with 0 gals', 'jetinsight'),
  ('HOU', 'Atlantic Aviation HOU', 'Atlantic Aviation', 'Citation X', 925, 374, 55, 80, 443, '$443, 0 night / 0% waived with 0 gals', 'jetinsight'),
  ('HOU', 'Galaxy FBO HOU', 'Galaxy FBO', 'Challenger 300', 295, 350, 40, 85, 330, '$330, 0 night / 0% waived with 0 gals', 'jetinsight'),
  ('HOU', 'Galaxy FBO HOU', 'Galaxy FBO', 'Citation X', 295, 350, 40, 80, 330, '$330, 0 night / 0% waived with 0 gals', 'jetinsight'),
  ('HOU', 'Houston, USA', 'Jet Aviation', 'Challenger 300', 550, 450, 50, 85, 323, '', 'jetinsight'),
  ('HOU', 'Houston, USA', 'Jet Aviation', 'Citation X', 660, 500, 30, 80, 201, '', 'jetinsight'),
  ('HOU', 'Million Air HOU', 'Million Air', 'Challenger 300', 750, 500, 200, 85, 250, '', 'jetinsight'),
  ('HOU', 'Million Air HOU', 'Million Air', 'Citation X', 750, 500, 200, 80, 250, '', 'jetinsight'),
  ('HOU', 'SIGNATURE HOUSTON', 'Signature Flight Support', 'Challenger 300', 880, 520, 36, 85, 255, '$255, 0 night / 0% waived with 0 gals', 'jetinsight'),
  ('HOU', 'SIGNATURE HOUSTON', 'Signature Flight Support', 'Citation X', 880, 520, 36, 80, 255, '$255, 0 night / 0% waived with 0 gals', 'jetinsight'),
  ('HOU', 'Wilson Air Center HOU', 'Wilson Air Center', 'Challenger 300', 300, 400, 30, 85, 300, '$300, 0.5 night / 50% waived with 800 gals', 'jetinsight'),
  ('HOU', 'Wilson Air Center HOU', 'Wilson Air Center', 'Citation X', 300, 400, 30, 80, 300, '$300, 0.5 night / 50% waived with 800 gals', 'jetinsight'),
  ('HPN', 'SIGNATURE WHITE PLAINS - TERMINAL EAST', 'Signature Flight Support', 'Challenger 300', 1660, 520, 52, NULL, NULL, '', 'jetinsight'),
  ('HPN', 'SIGNATURE WHITE PLAINS - TERMINAL WEST', 'Signature Flight Support', 'Challenger 300', 1660, 520, 52, NULL, NULL, '', 'jetinsight'),
  ('HPN', 'SIGNATURE WHITE PLAINS - TERMINAL EAST', 'Signature Flight Support', 'Citation X', 1660, 520, 52, NULL, NULL, '', 'jetinsight'),
  ('HPN', 'SIGNATURE WHITE PLAINS - TERMINAL WEST', 'Signature Flight Support', 'Citation X', 1660, 520, 52, NULL, NULL, '', 'jetinsight'),
  ('HPNE', 'Atlantic Aviation HPNE', 'Atlantic Aviation', 'Challenger 300', 1006, 404, 65, NULL, NULL, 'Complimentary (first hour) $44/hr (next 11 hours) then $24/hr', 'jetinsight'),
  ('HPNE', 'Atlantic Aviation HPNE', 'Atlantic Aviation', 'Citation X', 1063, 374, 65, NULL, NULL, 'Complimentary (first hour) $46/hr (next 11 hours) then $25/hr', 'jetinsight'),
  ('HPNW', 'Atlantic Aviation HPNW', 'Atlantic Aviation', 'Challenger 300', 1006, 404, 65, NULL, NULL, 'Complimentary (first hour) $44/hr (next 11 hours) then $24/hr', 'jetinsight'),
  ('HPNW', 'Atlantic Aviation HPNW', 'Atlantic Aviation', 'Citation X', 1063, 374, 65, NULL, NULL, 'Complimentary (first hour) $46/hr (next 11 hours) then $25/hr', 'jetinsight'),
  ('HSV', 'SIGNATURE HUNTSVILLE', 'Signature Flight Support', 'Challenger 300', 1460, 520, NULL, NULL, NULL, '', 'jetinsight'),
  ('HSV', 'SIGNATURE HUNTSVILLE', 'Signature Flight Support', 'Citation X', 1460, 520, NULL, NULL, NULL, '', 'jetinsight'),
  ('HWD', 'SIGNATURE HAYWARD', 'Signature Flight Support', 'Challenger 300', 730, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('HWD', 'SIGNATURE HAYWARD', 'Signature Flight Support', 'Citation X', 730, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('HXD', 'SIGNATURE HILTON HEAD', 'Signature Flight Support', 'Challenger 300', 1400, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('HXD', 'SIGNATURE HILTON HEAD', 'Signature Flight Support', 'Citation X', 1400, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('HYA', 'Atlantic Aviation HYA', 'Atlantic Aviation', 'Challenger 300', 1071, 404, 65, NULL, NULL, '{''unitPrice'': 1137.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('HYA', 'Atlantic Aviation HYA', 'Atlantic Aviation', 'Citation X', 1133, 374, 65, NULL, NULL, '{''unitPrice'': 1202.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('IAD', 'Atlantic Aviation IAD', 'Atlantic Aviation', 'Challenger 300', 1705, 404, 65, NULL, NULL, 'Complimentary (first hour) $74/hr (next 11 hours) then $40/hr', 'jetinsight'),
  ('IAD', 'Atlantic Aviation IAD', 'Atlantic Aviation', 'Citation X', 1803, 374, 65, NULL, NULL, 'Complimentary (first hour) $78/hr (next 11 hours) then $42/hr', 'jetinsight'),
  ('IAD', 'SIGNATURE WASHINGTON DULLES', 'Signature Flight Support', 'Citation X', 2240, 520, 49, NULL, NULL, '', 'jetinsight'),
  ('IAH', 'Atlantic Aviation IAH', 'Atlantic Aviation', 'Challenger 300', 874, 404, 55, NULL, NULL, 'Complimentary (first hour) $34/hr (next 11 hours) then $18/hr', 'jetinsight'),
  ('IAH', 'Atlantic Aviation IAH', 'Atlantic Aviation', 'Citation X', 925, 374, 55, NULL, NULL, 'Complimentary (first hour) $36/hr (next 11 hours) then $19/hr', 'jetinsight'),
  ('IAH', 'SIGNATURE HOUSTON', 'Signature Flight Support', 'Citation X', 1040, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('ICT', 'SIGNATURE WICHITA', 'Signature Flight Support', 'Challenger 300', 1560, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('ICT', 'SIGNATURE WICHITA', 'Signature Flight Support', 'Citation X', 1560, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('ILG', 'Atlantic Aviation ILG', 'Atlantic Aviation', 'Challenger 300', 984, 404, 55, NULL, NULL, 'Complimentary (first hour) $24/hr (next 11 hours) then $13/hr', 'jetinsight'),
  ('ILG', 'Atlantic Aviation ILG', 'Atlantic Aviation', 'Citation X', 1040, 374, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('ILM', 'Aero Center Wilmington ILM', 'Aero Center', 'Challenger 300', 575, 275, 15, 0, 232, '', 'jetinsight'),
  ('ILM', 'Aero Center Wilmington ILM', 'Aero Center', 'Citation X', 575, 275, 15, 0, 232, '', 'jetinsight'),
  ('ILM', 'Modern Aviation Wilmington', 'Modern Aviation', 'Challenger 300', 785, 450, 0, 0, 350, '', 'jetinsight'),
  ('ILM', 'Modern Aviation Wilmington', 'Modern Aviation', 'Citation X', 785, 450, 0, 0, 369, '', 'jetinsight'),
  ('IND', 'SIGNATURE INDIANAPOLIS', 'Signature Flight Support', 'Challenger 300', 1460, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('IND', 'SIGNATURE INDIANAPOLIS', 'Signature Flight Support', 'Citation X', 1460, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('INT', 'SIGNATURE WINSTON-SALEM', 'Signature Flight Support', 'Citation X', 1660, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('ISM', 'SIGNATURE KISSIMMEE', 'Signature Flight Support', 'Challenger 300', 730, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('ISM', 'SIGNATURE KISSIMMEE', 'Signature Flight Support', 'Citation X', 730, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('ITO', 'Atlantic Aviation ITO', 'Atlantic Aviation', 'Challenger 300', NULL, 404, 55, NULL, NULL, 'Complimentary (first hour) $34/hr (next 11 hours) then $18/hr', 'jetinsight'),
  ('ITO', 'Atlantic Aviation ITO', 'Atlantic Aviation', 'Citation X', NULL, 374, 55, NULL, NULL, 'Complimentary (first hour) $36/hr (next 11 hours) then $19/hr', 'jetinsight'),
  ('ITO', 'SIGNATURE HILO', 'Signature Flight Support', 'Challenger 300', 917.51, NULL, 38, NULL, NULL, '', 'jetinsight'),
  ('ITO', 'SIGNATURE HILO', 'Signature Flight Support', 'Citation X', 917.51, NULL, 38, NULL, NULL, '', 'jetinsight'),
  ('IXD', 'SIGNATURE NEW CENTURY', 'Signature Flight Support', 'Challenger 300', 1820, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('IXD', 'SIGNATURE NEW CENTURY', 'Signature Flight Support', 'Citation X', 1820, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('JAN', 'Atlantic Aviation JAN', 'Atlantic Aviation', 'Challenger 300', 1159, 404, 65, NULL, NULL, '{''unitPrice'': 459.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('JAN', 'Atlantic Aviation JAN', 'Atlantic Aviation', 'Citation X', 1225, 374, 65, NULL, NULL, '{''unitPrice'': 485.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('JAX', 'SIGNATURE JACKSONVILLE', 'Signature Flight Support', 'Challenger 300', 1460, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('JAX', 'SIGNATURE JACKSONVILLE', 'Signature Flight Support', 'Citation X', 1460, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('JFK', 'Modern Aviation New York', 'Modern Aviation', 'Challenger 300', 1150, 365, 67, 340, 300, '', 'jetinsight'),
  ('JFK', 'Modern Aviation New York', 'Modern Aviation', 'Citation X', 780, 480, 67, 1324, 100, '', 'jetinsight'),
  ('JZI', 'Atlantic Aviation JZI', 'Atlantic Aviation', 'Challenger 300', 1224, 404, 65, NULL, NULL, 'Complimentary (first hour) $34/hr (next 11 hours) then $18/hr', 'jetinsight'),
  ('JZI', 'Atlantic Aviation JZI', 'Atlantic Aviation', 'Citation X', 1295, 374, 65, NULL, NULL, 'Complimentary (first hour) $36/hr (next 11 hours) then $19/hr', 'jetinsight'),
  ('KOA', 'Atlantic Aviation KOA', 'Atlantic Aviation', 'Challenger 300', NULL, 404, 55, NULL, NULL, 'Complimentary (first hour) $42/hr (next 11 hours) then $23/hr', 'jetinsight'),
  ('KOA', 'Atlantic Aviation KOA', 'Atlantic Aviation', 'Citation X', NULL, 374, 55, NULL, NULL, 'Complimentary (first hour) $45/hr (next 11 hours) then $24/hr', 'jetinsight'),
  ('KOA', 'SIGNATURE KAILUA KONA', 'Signature Flight Support', 'Challenger 300', 2040.23, NULL, 38, NULL, NULL, '', 'jetinsight'),
  ('KOA', 'SIGNATURE KAILUA KONA', 'Signature Flight Support', 'Citation X', 2040.23, NULL, 38, NULL, NULL, '', 'jetinsight'),
  ('LAS', 'Atlantic Aviation LAS', 'Atlantic Aviation', 'Challenger 300', 1530, 404, 65, NULL, NULL, 'Complimentary (first hour) $86/hr (next 11 hours) then $46/hr', 'jetinsight'),
  ('LAS', 'Atlantic Aviation LAS', 'Atlantic Aviation', 'Citation X', 1618, 374, 65, NULL, NULL, 'Complimentary (first hour) $91/hr (next 11 hours) then $49/hr', 'jetinsight'),
  ('LAS', 'SIGNATURE LAS VEGAS', 'Signature Flight Support', 'Challenger 300', 1920, 520, 43, NULL, NULL, '', 'jetinsight'),
  ('LAS', 'SIGNATURE LAS VEGAS', 'Signature Flight Support', 'Citation X', 1920, 520, 43, NULL, NULL, '', 'jetinsight'),
  ('LAX', 'Atlantic Aviation LAX', 'Atlantic Aviation', 'Challenger 300', 1530, 404, 65, NULL, NULL, 'Complimentary (first hour) $89/hr (next 11 hours) then $48/hr', 'jetinsight'),
  ('LAX', 'Atlantic Aviation LAX', 'Atlantic Aviation', 'Citation X', 1618, 374, 65, NULL, NULL, 'Complimentary (first hour) $94/hr (next 11 hours) then $51/hr', 'jetinsight'),
  ('LAX', 'SIGNATURE LOS ANGELES', 'Signature Flight Support', 'Citation X', 1920, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('LEX', 'SIGNATURE LEXINGTON', 'Signature Flight Support', 'Challenger 300', 1907.4, 520, 38.76, NULL, NULL, '', 'jetinsight'),
  ('LEX', 'SIGNATURE LEXINGTON', 'Signature Flight Support', 'Citation X', 1907.4, 520, 38.76, NULL, NULL, '', 'jetinsight'),
  ('LFT', 'SIGNATURE LAFAYETTE', 'Signature Flight Support', 'Challenger 300', 1200, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('LFT', 'SIGNATURE LAFAYETTE', 'Signature Flight Support', 'Citation X', 1200, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('LGA', 'Modern Aviation New York', 'Modern Aviation', 'Challenger 300', 1100, 410, 50, 943, 165, '', 'jetinsight'),
  ('LGA', 'Modern Aviation New York', 'Modern Aviation', 'Citation X', 1100, 410, 50, 1501, 165, '', 'jetinsight'),
  ('LGB', 'Atlantic Aviation LGB', 'Atlantic Aviation', 'Challenger 300', 1530, 404, 55, NULL, NULL, 'Complimentary (first hour) $51/hr (next 11 hours) then $27/hr', 'jetinsight'),
  ('LGB', 'Atlantic Aviation LGB', 'Atlantic Aviation', 'Citation X', 1618, 374, 55, NULL, NULL, 'Complimentary (first hour) $53/hr (next 11 hours) then $29/hr', 'jetinsight'),
  ('LGB', 'SIGNATURE LONG BEACH', 'Signature Flight Support', 'Challenger 300', 1920, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('LGB', 'SIGNATURE LONG BEACH', 'Signature Flight Support', 'Citation X', 1920, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('LIH', 'Atlantic Aviation LIH', 'Atlantic Aviation', 'Challenger 300', NULL, 404, 55, NULL, NULL, 'Complimentary (first hour) $42/hr (next 11 hours) then $23/hr', 'jetinsight'),
  ('LIH', 'Atlantic Aviation LIH', 'Atlantic Aviation', 'Citation X', NULL, 374, 55, NULL, NULL, 'Complimentary (first hour) $45/hr (next 11 hours) then $24/hr', 'jetinsight'),
  ('LIH', 'SIGNATURE LIHUE', 'Signature Flight Support', 'Challenger 300', 984.29, NULL, 38, NULL, NULL, '', 'jetinsight'),
  ('LIH', 'SIGNATURE LIHUE', 'Signature Flight Support', 'Citation X', 984.29, NULL, 38, NULL, NULL, '', 'jetinsight'),
  ('LIT', 'Atlantic Aviation LIT', 'Atlantic Aviation', 'Challenger 300', 874, 404, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('LIT', 'Atlantic Aviation LIT', 'Atlantic Aviation', 'Citation X', 925, 374, 55, NULL, NULL, 'Complimentary (first hour) $27/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('LIT', 'SIGNATURE LITTLE ROCK', 'Signature Flight Support', 'Challenger 300', 940, 520, 26, NULL, NULL, '', 'jetinsight'),
  ('LIT', 'SIGNATURE LITTLE ROCK', 'Signature Flight Support', 'Citation X', 940, 520, 26, NULL, NULL, '', 'jetinsight'),
  ('LNK', 'Atlantic Aviation LNK', 'Atlantic Aviation', 'Challenger 300', 984, 404, 55, NULL, NULL, '{''unitPrice'': 328.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('LNK', 'Atlantic Aviation LNK', 'Atlantic Aviation', 'Citation X', 1040, 374, 55, NULL, NULL, '{''unitPrice'': 347.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('LNY', 'Atlantic Aviation LNY', 'Atlantic Aviation', 'Challenger 300', NULL, 404, 55, NULL, NULL, 'Complimentary (first hour) $42/hr (next 11 hours) then $23/hr', 'jetinsight'),
  ('LNY', 'Atlantic Aviation LNY', 'Atlantic Aviation', 'Citation X', NULL, 374, 55, NULL, NULL, 'Complimentary (first hour) $45/hr (next 11 hours) then $24/hr', 'jetinsight'),
  ('LNY', 'SIGNATURE LANAI CITY', 'Signature Flight Support', 'Challenger 300', 1032.19, NULL, 38, NULL, NULL, '', 'jetinsight'),
  ('LNY', 'SIGNATURE LANAI CITY', 'Signature Flight Support', 'Citation X', 1032.19, NULL, 38, NULL, NULL, '', 'jetinsight'),
  ('LRD', 'SIGNATURE LAREDO', 'Signature Flight Support', 'Citation X', 1400, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('LUK', 'SIGNATURE CINCINNATI', 'Signature Flight Support', 'Challenger 300', 1510, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('LUK', 'SIGNATURE CINCINNATI', 'Signature Flight Support', 'Citation X', 1510, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('MAF', 'SIGNATURE MIDLAND', 'Signature Flight Support', 'Citation X', 1350, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('MBJ', 'SIGNATURE MONTEGO BAY', 'Signature Flight Support', 'Challenger 300', 1510, NULL, 250, NULL, NULL, '', 'jetinsight'),
  ('MBJ', 'SIGNATURE MONTEGO BAY', 'Signature Flight Support', 'Citation X', 1510, NULL, 250, NULL, NULL, '', 'jetinsight'),
  ('MCI', 'SIGNATURE KANSAS CITY', 'Signature Flight Support', 'Challenger 300', 1980, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('MCI', 'SIGNATURE KANSAS CITY', 'Signature Flight Support', 'Citation X', 1980, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('MCO', 'Atlantic Aviation MCO', 'Atlantic Aviation', 'Challenger 300', 874, 404, 55, NULL, NULL, '{''unitPrice'': 415.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('MCO', 'Atlantic Aviation MCO', 'Atlantic Aviation', 'Citation X', 925, 374, 55, NULL, NULL, '{''unitPrice'': 439.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('MCO', 'SIGNATURE ORLANDO', 'Signature Flight Support', 'Challenger 300', 1040, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('MCO', 'SIGNATURE ORLANDO', 'Signature Flight Support', 'Citation X', 1040, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('MDW', 'Atlantic Aviation MDW', 'Atlantic Aviation', 'Challenger 300', 1486, 404, 65, NULL, NULL, 'Complimentary (first hour) $74/hr (next 11 hours) then $40/hr', 'jetinsight'),
  ('MDW', 'Atlantic Aviation MDW', 'Atlantic Aviation', 'Citation X', 1572, 374, 65, NULL, NULL, 'Complimentary (first hour) $78/hr (next 11 hours) then $42/hr', 'jetinsight'),
  ('MDW', 'SIGNATURE CHICAGO MIDWAY', 'Signature Flight Support', 'Challenger 300', 2307.2, 520, 43, NULL, NULL, '', 'jetinsight'),
  ('MDW', 'SIGNATURE CHICAGO MIDWAY', 'Signature Flight Support', 'Citation X', 2307.2, 520, 43, NULL, NULL, '', 'jetinsight'),
  ('MEM', 'SIGNATURE MEMPHIS', 'Signature Flight Support', 'Challenger 300', 1250, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('MEM', 'SIGNATURE MEMPHIS', 'Signature Flight Support', 'Citation X', 1250, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('MHR', 'Mather Jet Center MHR', 'Mather Jet Center', 'Challenger 300', 0, 0, 0, 0, 0, '', 'jetinsight'),
  ('MHR', 'Mather Jet Center MHR', 'Mather Jet Center', 'Citation X', 0, 0, 0, 0, 0, '', 'jetinsight'),
  ('MHR', 'Modern Aviation Mather', 'Modern Aviation', 'Challenger 300', 780, 410, 60, 0, 350, '$350, 0 night / 0% waived with 0 gals', 'jetinsight'),
  ('MHR', 'Modern Aviation Mather', 'Modern Aviation', 'Citation X', 780, 410, 60, 0, 369, '$369, 0 night / 0% waived with 0 gals', 'jetinsight'),
  ('MHT', 'SIGNATURE MANCHESTER-BOSTON', 'Signature Flight Support', 'Challenger 300', 1920, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('MHT', 'SIGNATURE MANCHESTER-BOSTON', 'Signature Flight Support', 'Citation X', 1920, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('MIA', 'SIGNATURE MIAMI', 'Signature Flight Support', 'Citation X', 1980, 520, 43, NULL, NULL, '', 'jetinsight'),
  ('MKC', 'Atlantic Aviation MKC', 'Atlantic Aviation', 'Challenger 300', 1377, 404, 55, NULL, NULL, 'Complimentary (first hour) $30/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('MKC', 'Atlantic Aviation MKC', 'Atlantic Aviation', 'Citation X', 1456, 374, 55, NULL, NULL, 'Complimentary (first hour) $32/hr (next 11 hours) then $17/hr', 'jetinsight'),
  ('MKC', 'SIGNATURE KANSAS CITY DOWNTOWN', 'Signature Flight Support', 'Challenger 300', 1980, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('MKC', 'SIGNATURE KANSAS CITY DOWNTOWN', 'Signature Flight Support', 'Citation X', 1980, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('MKE', 'Avflight Milwaukee MKE', 'Avflight', 'Challenger 300', 840, 450, 55, 199, 200, '', 'jetinsight'),
  ('MKE', 'Avflight Milwaukee MKE', 'Avflight', 'Citation X', 840, 450, 56, 180, 200, '', 'jetinsight'),
  ('MKE', 'Milwaukee, USA', 'Jet Aviation', 'Challenger 300', 900, 480, 41, 199, 195, '', 'jetinsight'),
  ('MKE', 'Milwaukee, USA', 'Jet Aviation', 'Citation X', 900, 480, 41, 180, 201, '', 'jetinsight'),
  ('MKE', 'SIGNATURE MILWAUKEE', 'Signature Flight Support', 'Challenger 300', 2136.42, 520, 46, 199, 280, '', 'jetinsight'),
  ('MKE', 'SIGNATURE MILWAUKEE', 'Signature Flight Support', 'Citation X', 2136.42, 520, 46, 180, 280, '', 'jetinsight'),
  ('MMU', 'Atlantic Aviation MMU', 'Atlantic Aviation', 'Challenger 300', 984, 404, 55, NULL, NULL, 'Complimentary (first hour) $22/hr (next 11 hours) then $12/hr', 'jetinsight'),
  ('MMU', 'Atlantic Aviation MMU', 'Atlantic Aviation', 'Citation X', 1040, 374, 55, NULL, NULL, 'Complimentary (first hour) $23/hr (next 11 hours) then $13/hr', 'jetinsight'),
  ('MMU', 'SIGNATURE MORRISTOWN', 'Signature Flight Support', 'Challenger 300', 1660, 520, 41, NULL, NULL, '', 'jetinsight'),
  ('MMU', 'SIGNATURE MORRISTOWN', 'Signature Flight Support', 'Citation X', 1660, 520, 41, NULL, NULL, '', 'jetinsight'),
  ('MOB', 'SIGNATURE MOBILE', 'Signature Flight Support', 'Challenger 300', 1460, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('MOB', 'SIGNATURE MOBILE', 'Signature Flight Support', 'Citation X', 1460, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('MQS', 'SIGNATURE COATESVILLE', 'Signature Flight Support', 'Citation X', 1510, 520, 43, NULL, NULL, '', 'jetinsight'),
  ('MSP', 'SIGNATURE MINNEAPOLIS-ST. PAUL', 'Signature Flight Support', 'Challenger 300', 2080, 520, 43, NULL, NULL, '', 'jetinsight'),
  ('MSP', 'SIGNATURE MINNEAPOLIS-ST. PAUL', 'Signature Flight Support', 'Citation X', 2080, 520, 43, NULL, NULL, '', 'jetinsight'),
  ('MSY', 'Atlantic Aviation MSY', 'Atlantic Aviation', 'Challenger 300', 874, 404, 55, NULL, NULL, 'Complimentary (first hour) $24/hr (next 11 hours) then $13/hr', 'jetinsight'),
  ('MSY', 'Atlantic Aviation MSY', 'Atlantic Aviation', 'Citation X', 925, 374, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('MSY', 'SIGNATURE NEW ORLEANS', 'Signature Flight Support', 'Challenger 300', 940, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('MSY', 'SIGNATURE NEW ORLEANS', 'Signature Flight Support', 'Citation X', 940, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('MTJ', 'Atlantic Aviation MTJ', 'Atlantic Aviation', 'Challenger 300', 1093, 404, 55, NULL, NULL, 'Complimentary (first hour) $29/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('MTJ', 'Atlantic Aviation MTJ', 'Atlantic Aviation', 'Citation X', 1156, 374, 55, NULL, NULL, 'Complimentary (first hour) $30/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('NEV', 'SIGNATURE NEVIS', 'Signature Flight Support', 'Challenger 300', 1400, NULL, 32, NULL, NULL, '', 'jetinsight'),
  ('NEV', 'SIGNATURE NEVIS', 'Signature Flight Support', 'Citation X', 1400, NULL, 32, NULL, NULL, '', 'jetinsight'),
  ('NEW', 'SIGNATURE NEW ORLEANS LAKEFRONT', 'Signature Flight Support', 'Challenger 300', 1140, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('NEW', 'SIGNATURE NEW ORLEANS LAKEFRONT', 'Signature Flight Support', 'Citation X', 1140, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('OAK', 'SIGNATURE OAKLAND', 'Signature Flight Support', 'Citation X', 1660, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('OGG', 'Atlantic Aviation OGG', 'Atlantic Aviation', 'Challenger 300', NULL, 404, 55, NULL, NULL, 'Complimentary (first hour) $42/hr (next 11 hours) then $23/hr', 'jetinsight'),
  ('OGG', 'Atlantic Aviation OGG', 'Atlantic Aviation', 'Citation X', NULL, 374, 55, NULL, NULL, 'Complimentary (first hour) $45/hr (next 11 hours) then $24/hr', 'jetinsight'),
  ('OGG', 'SIGNATURE KAHULUI MAUI', 'Signature Flight Support', 'Challenger 300', 1355.41, NULL, 38, NULL, NULL, '', 'jetinsight'),
  ('OGG', 'SIGNATURE KAHULUI MAUI', 'Signature Flight Support', 'Citation X', 1355.41, NULL, 38, NULL, NULL, '', 'jetinsight'),
  ('OKC', 'Atlantic Aviation OKC', 'Atlantic Aviation', 'Challenger 300', 1049, 404, 55, NULL, NULL, 'Complimentary (first hour) $27/hr (next 11 hours) then $15/hr', 'jetinsight'),
  ('OKC', 'Atlantic Aviation OKC', 'Atlantic Aviation', 'Citation X', 1110, 374, 55, NULL, NULL, 'Complimentary (first hour) $29/hr (next 11 hours) then $15/hr', 'jetinsight'),
  ('OMA', 'Atlantic Aviation OMA', 'Atlantic Aviation', 'Challenger 300', 1115, 404, 55, NULL, NULL, '{''unitPrice'': 372.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('OMA', 'Atlantic Aviation OMA', 'Atlantic Aviation', 'Citation X', 1179, 374, 55, NULL, NULL, '{''unitPrice'': 393.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('OMA', 'SIGNATURE OMAHA', 'Signature Flight Support', 'Challenger 300', 1460, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('OMA', 'SIGNATURE OMAHA', 'Signature Flight Support', 'Citation X', 1460, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('OPF', 'Atlantic Aviation OPF', 'Atlantic Aviation', 'Challenger 300', 1093, 404, 55, 0, 874, '{''unitPrice'': 874.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('OPF', 'Atlantic Aviation OPF', 'Atlantic Aviation', 'Citation X', 1156, 374, 55, 0, 925, '{''unitPrice'': 925.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('OPF', 'Embassair OPF', 'Embassair', 'Challenger 300', 856, 800, 60, 0, 503, '', 'jetinsight'),
  ('OPF', 'Embassair OPF', 'Embassair', 'Citation X', 856, 800, 60, 0, 503, '', 'jetinsight'),
  ('OPF', 'Miami — Opa Locka, USA', 'Jet Aviation', 'Challenger 300', 800, 450, 50, 0, 692, '', 'jetinsight'),
  ('OPF', 'Miami — Opa Locka, USA', 'Jet Aviation', 'Citation X', 800, 450, 50, 0, 692, '', 'jetinsight'),
  ('OPF', 'SIGNATURE OPA-LOCKA', 'Signature Flight Support', 'Challenger 300', 1400, 520, 38, 0, 790, '', 'jetinsight'),
  ('OPF', 'SIGNATURE OPA-LOCKA', 'Signature Flight Support', 'Citation X', 1400, 520, 38, 0, 790, '', 'jetinsight'),
  ('OPF', 'Fontainebleau by Sky Service OPF', 'Sky Service', 'Challenger 300', 0, 0, 39, 0, 0, '$0, 1 night / 0 gals', 'jetinsight'),
  ('OPF', 'Fontainebleau by Sky Service OPF', 'Sky Service', 'Citation X', 0, 0, 39, 0, 0, '$0, 1 night / 0 gals', 'jetinsight'),
  ('ORD', 'SIGNATURE CHICAGO O''HARE', 'Signature Flight Support', 'Challenger 300', 2629, 520, 46, NULL, NULL, '', 'jetinsight'),
  ('ORD', 'SIGNATURE CHICAGO O''HARE', 'Signature Flight Support', 'Citation X', 2629, 520, 46, NULL, NULL, '', 'jetinsight'),
  ('ORF', 'SIGNATURE NORFOLK', 'Signature Flight Support', 'Citation X', 1770, 520, 46, NULL, NULL, '', 'jetinsight'),
  ('ORH', 'Atlantic Aviation ORH', 'Atlantic Aviation', 'Challenger 300', 1049, 404, 55, NULL, NULL, '{''unitPrice'': 459.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('ORH', 'Atlantic Aviation ORH', 'Atlantic Aviation', 'Citation X', 1110, 374, 55, NULL, NULL, '{''unitPrice'': 485.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('ORL', 'Atlantic Aviation ORL', 'Atlantic Aviation', 'Challenger 300', 962, 404, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('ORL', 'Atlantic Aviation ORL', 'Atlantic Aviation', 'Citation X', 1017, 374, 55, NULL, NULL, 'Complimentary (first hour) $27/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('OXC', 'Atlantic Aviation OXC', 'Atlantic Aviation', 'Challenger 300', 1137, 404, 65, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('OXC', 'Atlantic Aviation OXC', 'Atlantic Aviation', 'Citation X', 1202, 374, 65, NULL, NULL, 'Complimentary (first hour) $27/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('PBI', 'Atlantic Aviation PBI', 'Atlantic Aviation', 'Challenger 300', 1377, 404, 165, 64, 1646, 'Complimentary (first hour) $94/hr (next 11 hours) then $51/hr', 'jetinsight'),
  ('PBI', 'Atlantic Aviation PBI', 'Atlantic Aviation', 'Citation X', 1456, 374, 165, 69, 1295, 'Complimentary (first hour) $100/hr (next 11 hours) then $54/hr', 'jetinsight'),
  ('PBI', 'Palm Beach, USA', 'Jet Aviation', 'Challenger 300', 950, 450, 50, 64, 738, '', 'jetinsight'),
  ('PBI', 'Palm Beach, USA', 'Jet Aviation', 'Citation X', 950, 450, 50, 69, 738, '', 'jetinsight'),
  ('PBI', 'SIGNATURE PALM BEACH', 'Signature Flight Support', 'Challenger 300', 1820, 520, 43, 64, 1275, '', 'jetinsight'),
  ('PBI', 'SIGNATURE PALM BEACH NORTH', 'Signature Flight Support', 'Challenger 300', 1980, 520, 43, 64, 1275, '', 'jetinsight'),
  ('PBI', 'SIGNATURE PALM BEACH', 'Signature Flight Support', 'Citation X', 1820, 520, 43, 69, 1275, '', 'jetinsight'),
  ('PBI', 'SIGNATURE PALM BEACH NORTH', 'Signature Flight Support', 'Citation X', 1980, 520, 43, 69, 1275, '', 'jetinsight'),
  ('PDK', 'Atlantic Aviation PDK', 'Atlantic Aviation', 'Challenger 300', 874, 404, 55, NULL, NULL, 'Complimentary (first hour) $29/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('PDK', 'Atlantic Aviation PDK', 'Atlantic Aviation', 'Citation X', 925, 374, 55, NULL, NULL, 'Complimentary (first hour) $30/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('PDK', 'SIGNATURE ATLANTA DEKALB PEACHTREE', 'Signature Flight Support', 'Challenger 300', 1090, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('PDK', 'SIGNATURE ATLANTA DEKALB PEACHTREE', 'Signature Flight Support', 'Citation X', 1090, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('PDX', 'Atlantic Aviation PDX', 'Atlantic Aviation', 'Challenger 300', 1312, 404, 65, NULL, NULL, 'Complimentary (first hour) $68/hr (next 11 hours) then $36/hr', 'jetinsight'),
  ('PDX', 'Atlantic Aviation PDX', 'Atlantic Aviation', 'Citation X', 1387, 374, 65, NULL, NULL, 'Complimentary (first hour) $72/hr (next 11 hours) then $38/hr', 'jetinsight'),
  ('PGA', 'American Aviation PGA', 'American Aviation', 'Challenger 300', 0, NULL, 0, 0, 40, '', 'jetinsight'),
  ('PGA', 'American Aviation PGA', 'American Aviation', 'Citation X', 0, NULL, 0, 0, 40, '', 'jetinsight'),
  ('PGA', 'Classic Aviation PGA', 'Classic Aviation', 'Challenger 300', 0, NULL, 0, 0, 50, '', 'jetinsight'),
  ('PGA', 'Classic Aviation PGA', 'Classic Aviation', 'Citation X', 0, NULL, 0, 0, 50, '', 'jetinsight'),
  ('PGA', 'Million Air PGA', 'Million Air', 'Challenger 300', 400, 300, 0, 0, 100, '', 'jetinsight'),
  ('PGA', 'Million Air PGA', 'Million Air', 'Citation X', 400, 300, 0, 0, 100, '', 'jetinsight'),
  ('PHF', 'Atlantic Aviation PHF', 'Atlantic Aviation', 'Challenger 300', 1093, 404, 55, NULL, NULL, 'Complimentary (first hour) $27/hr (next 11 hours) then $15/hr', 'jetinsight'),
  ('PHF', 'Atlantic Aviation PHF', 'Atlantic Aviation', 'Citation X', 1156, 374, 55, NULL, NULL, 'Complimentary (first hour) $29/hr (next 11 hours) then $15/hr', 'jetinsight'),
  ('PHK', 'SIGNATURE PALM BEACH COUNTY', 'Signature Flight Support', 'Citation X', 1660, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('PHL', 'Atlantic Aviation PHL', 'Atlantic Aviation', 'Challenger 300', 1268, 404, 65, NULL, NULL, 'Complimentary (first hour) $67/hr (next 11 hours) then $36/hr', 'jetinsight'),
  ('PHL', 'Atlantic Aviation PHL', 'Atlantic Aviation', 'Citation X', 1341, 374, 65, NULL, NULL, 'Complimentary (first hour) $71/hr (next 11 hours) then $39/hr', 'jetinsight'),
  ('PHX', 'Cutter Aviation PHX', 'Cutter Aviation', 'Challenger 300', 250, 250, 35, 65, 0, '$0, 1 night / 0 gals', 'jetinsight'),
  ('PHX', 'Cutter Aviation PHX', 'Cutter Aviation', 'Citation X', 175, 100, 35, 564, 0, '$0, 1 night / 0 gals', 'jetinsight'),
  ('PHX', 'Jackson Jet Center PHX', 'Jackson Jet Center', 'Challenger 300', 450, 435, 50, 65, 264, '', 'jetinsight'),
  ('PHX', 'Jackson Jet Center PHX', 'Jackson Jet Center', 'Citation X', 445, 375, 50, 564, 264, '', 'jetinsight'),
  ('PIE', 'SIGNATURE ST. PETE-CLEARWATER', 'Signature Flight Support', 'Citation X', 1140, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('PIT', 'Atlantic Aviation PIT', 'Atlantic Aviation', 'Challenger 300', 1246, 404, 65, NULL, NULL, 'Complimentary (first hour) $34/hr (next 11 hours) then $18/hr', 'jetinsight'),
  ('PIT', 'Atlantic Aviation PIT', 'Atlantic Aviation', 'Citation X', 1318, 374, 65, NULL, NULL, 'Complimentary (first hour) $36/hr (next 11 hours) then $19/hr', 'jetinsight'),
  ('PLS', 'Atlantic Aviation PLS', 'Atlantic Aviation', 'Challenger 300', 1508, 404, 100, NULL, NULL, '{''unitPrice'': 372.0, ''comment'': ''7-Parking/Tiedown''}', 'jetinsight'),
  ('PLS', 'Atlantic Aviation PLS', 'Atlantic Aviation', 'Citation X', 1595, 374, 100, NULL, NULL, '{''unitPrice'': 393.0, ''comment'': ''7-Parking/Tiedown''}', 'jetinsight'),
  ('PNE', 'Atlantic Aviation PNE', 'Atlantic Aviation', 'Challenger 300', 1049, 404, 55, NULL, NULL, 'Complimentary (first hour) $24/hr (next 11 hours) then $13/hr', 'jetinsight'),
  ('PNE', 'Atlantic Aviation PNE', 'Atlantic Aviation', 'Citation X', 1110, 374, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('PSP', 'Atlantic Aviation PSP', 'Atlantic Aviation', 'Challenger 300', 1093, 404, 55, NULL, NULL, '{''unitPrice'': 415.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('PSP', 'Atlantic Aviation PSP', 'Atlantic Aviation', 'Citation X', 1156, 374, 55, NULL, NULL, '{''unitPrice'': 439.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('PSP', 'SIGNATURE PALM SPRINGS', 'Signature Flight Support', 'Challenger 300', 1820, 520, 40, NULL, NULL, '', 'jetinsight'),
  ('PSP', 'SIGNATURE PALM SPRINGS', 'Signature Flight Support', 'Citation X', 1820, 520, 40, NULL, NULL, '', 'jetinsight'),
  ('PTY', 'SIGNATURE PANAMA CITY', 'Signature Flight Support', 'Challenger 300', 1207.8, NULL, 54.9, NULL, NULL, '', 'jetinsight'),
  ('PTY', 'SIGNATURE PANAMA CITY', 'Signature Flight Support', 'Citation X', 1207.8, NULL, 54.9, NULL, NULL, '', 'jetinsight'),
  ('PVD', 'Atlantic Aviation PVD', 'Atlantic Aviation', 'Challenger 300', 1312, 404, 55, NULL, NULL, 'Complimentary (first hour) $37/hr (next 11 hours) then $20/hr', 'jetinsight'),
  ('PVD', 'Atlantic Aviation PVD', 'Atlantic Aviation', 'Citation X', 1387, 374, 55, NULL, NULL, 'Complimentary (first hour) $39/hr (next 11 hours) then $21/hr', 'jetinsight'),
  ('PVU', 'SIGNATURE PROVO', 'Signature Flight Support', 'Challenger 300', 1660, 520, 26, NULL, NULL, '', 'jetinsight'),
  ('PVU', 'SIGNATURE PROVO', 'Signature Flight Support', 'Citation X', 1660, 520, 26, NULL, NULL, '', 'jetinsight'),
  ('PWA', 'Atlantic Aviation PWA', 'Atlantic Aviation', 'Challenger 300', 918, 404, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('PWA', 'Atlantic Aviation PWA', 'Atlantic Aviation', 'Citation X', 971, 374, 55, NULL, NULL, 'Complimentary (first hour) $27/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('PWK', 'Atlantic Aviation PWK', 'Atlantic Aviation', 'Challenger 300', 1312, 404, 55, NULL, NULL, 'Complimentary (first hour) $29/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('PWK', 'Atlantic Aviation PWK', 'Atlantic Aviation', 'Citation X', 1387, 374, 55, NULL, NULL, 'Complimentary (first hour) $30/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('PWK', 'SIGNATURE CHICAGO EXECUTIVE', 'Signature Flight Support', 'Challenger 300', 1980, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('PWK', 'SIGNATURE CHICAGO EXECUTIVE', 'Signature Flight Support', 'Citation X', 1980, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('RDU', 'Atlantic Aviation RDU', 'Atlantic Aviation', 'Challenger 300', 1115, 404, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('RDU', 'Atlantic Aviation RDU', 'Atlantic Aviation', 'Citation X', 1179, 374, 55, NULL, NULL, 'Complimentary (first hour) $27/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('RDU', 'SIGNATURE RALEIGH-DURHAM', 'Signature Flight Support', 'Citation X', 1510, 520, 47, NULL, NULL, '', 'jetinsight'),
  ('RIC', 'Million Air RIC', 'Million Air', 'Challenger 300', 350, 400, 0, 0, 1, '', 'jetinsight'),
  ('RIC', 'Million Air RIC', 'Million Air', 'Citation X', 350, 400, 0, 0, 1, '', 'jetinsight'),
  ('RIC', 'Richmond Jet Center RIC', 'Richmond Jet Center', 'Challenger 300', 318, 318, 0, 0, 318, '$318, 1 night / 318 gals', 'jetinsight'),
  ('RIC', 'Richmond Jet Center RIC', 'Richmond Jet Center', 'Citation X', 318, 318, 0, 0, 318, '$318, 1 night / 318 gals', 'jetinsight'),
  ('RIL', 'Atlantic Aviation RIL', 'Atlantic Aviation', 'Challenger 300', 1355, 404, 55, NULL, NULL, '{''unitPrice'': 721.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('RIL', 'Atlantic Aviation RIL', 'Atlantic Aviation', 'Citation X', 1433, 374, 55, NULL, NULL, '{''unitPrice'': 763.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('RNO', 'Atlantic Aviation RNO', 'Atlantic Aviation', 'Challenger 300', 962, 404, 55, NULL, NULL, 'Complimentary (first hour) $27/hr (next 11 hours) then $15/hr', 'jetinsight'),
  ('RNO', 'Atlantic Aviation RNO', 'Atlantic Aviation', 'Citation X', 1017, 374, 55, NULL, NULL, 'Complimentary (first hour) $29/hr (next 11 hours) then $15/hr', 'jetinsight'),
  ('ROA', 'SIGNATURE ROANOKE', 'Signature Flight Support', 'Citation X', 1820, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('RST', 'SIGNATURE ROCHESTER', 'Signature Flight Support', 'Challenger 300', 1720, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('RST', 'SIGNATURE ROCHESTER', 'Signature Flight Support', 'Citation X', 1720, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('SAF', 'Atlantic Aviation SAF', 'Atlantic Aviation', 'Challenger 300', 831, 404, 55, NULL, NULL, '{''unitPrice'': 0.0, ''comment'': ''Do not use at SAF''}', 'jetinsight'),
  ('SAF', 'Atlantic Aviation SAF', 'Atlantic Aviation', 'Citation X', 878, 374, 55, NULL, NULL, '{''unitPrice'': 0.0, ''comment'': ''Do not use at SAF''}', 'jetinsight'),
  ('SAF', 'SIGNATURE SANTA FE', 'Signature Flight Support', 'Challenger 300', 952.05, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('SAF', 'SIGNATURE SANTA FE', 'Signature Flight Support', 'Citation X', 952.05, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('SAN', 'SIGNATURE SAN DIEGO', 'Signature Flight Support', 'Citation X', 2440, 520, 43, NULL, NULL, '', 'jetinsight'),
  ('SAT', 'SIGNATURE SAN ANTONIO - NORTH', 'Signature Flight Support', 'Citation X', 1510, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('SAV', 'SIGNATURE SAVANNAH', 'Signature Flight Support', 'Challenger 300', 1400, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('SAV', 'SIGNATURE SAVANNAH', 'Signature Flight Support', 'Citation X', 1400, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('SBA', 'Atlantic Aviation SBA', 'Atlantic Aviation', 'Challenger 300', 1071, 404, 65, NULL, NULL, 'Complimentary (first hour) $24/hr (next 11 hours) then $13/hr', 'jetinsight'),
  ('SBA', 'Atlantic Aviation SBA', 'Atlantic Aviation', 'Citation X', 1133, 374, 65, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('SBA', 'SIGNATURE SANTA BARBARA', 'Signature Flight Support', 'Challenger 300', 1350, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('SBA', 'SIGNATURE SANTA BARBARA', 'Signature Flight Support', 'Citation X', 1350, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('SBN', 'Atlantic Aviation SBN', 'Atlantic Aviation', 'Challenger 300', 1180, 404, 55, NULL, NULL, 'Complimentary (first hour) $29/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('SBN', 'Atlantic Aviation SBN', 'Atlantic Aviation', 'Citation X', 1248, 374, 55, NULL, NULL, 'Complimentary (first hour) $30/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('SBN', 'SIGNATURE SOUTH BEND', 'Signature Flight Support', 'Challenger 300', 1510, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('SBN', 'SIGNATURE SOUTH BEND', 'Signature Flight Support', 'Citation X', 1510, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('SCK', 'Atlantic Aviation SCK', 'Atlantic Aviation', 'Challenger 300', 1202, 404, 65, NULL, NULL, 'Complimentary (first hour) $29/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('SCK', 'Atlantic Aviation SCK', 'Atlantic Aviation', 'Citation X', 1271, 374, 65, NULL, NULL, 'Complimentary (first hour) $30/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('SDF', 'Atlantic Aviation SDF', 'Atlantic Aviation', 'Challenger 300', 984, 404, 65, NULL, NULL, '{''unitPrice'': 415.0, ''comment'': ''RON Fee''}', 'jetinsight'),
  ('SDF', 'Atlantic Aviation SDF', 'Atlantic Aviation', 'Citation X', 1040, 374, 65, NULL, NULL, '{''unitPrice'': 439.0, ''comment'': ''RON Fee''}', 'jetinsight'),
  ('SDL', 'Atlantic Aviation SDL', 'Atlantic Aviation', 'Challenger 300', 874, 404, 65, 61, 647, 'Complimentary (first hour) $37/hr (next 11 hours) then $20/hr', 'jetinsight'),
  ('SDL', 'Atlantic Aviation SDL', 'Atlantic Aviation', 'Citation X', 925, 374, 65, 55, 681, 'Complimentary (first hour) $39/hr (next 11 hours) then $21/hr', 'jetinsight'),
  ('SDL', 'Scottsdale, USA', 'Jet Aviation', 'Challenger 300', 725, 450, 35, 61, 375, '', 'jetinsight'),
  ('SDL', 'Scottsdale, USA', 'Jet Aviation', 'Citation X', 725, 450, 35, 55, 375, '', 'jetinsight'),
  ('SDL', 'SIGNATURE SCOTTSDALE', 'Signature Flight Support', 'Challenger 300', 1040, 520, 36, 61, 750, '', 'jetinsight'),
  ('SDL', 'SIGNATURE SCOTTSDALE', 'Signature Flight Support', 'Citation X', 1040, 520, 36, 55, 750, '', 'jetinsight'),
  ('SEA', 'SIGNATURE SEATTLE TACOMA', 'Signature Flight Support', 'Challenger 300', 2340, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('SEA', 'SIGNATURE SEATTLE TACOMA', 'Signature Flight Support', 'Citation X', 2340, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('SFO', 'SIGNATURE SAN FRANCISCO', 'Signature Flight Support', 'Challenger 300', 1158, 456, 41, NULL, NULL, '', 'jetinsight'),
  ('SFO', 'SIGNATURE SAN FRANCISCO', 'Signature Flight Support', 'Citation X', 1158, 456, 41, NULL, NULL, '', 'jetinsight'),
  ('SGJ', 'Atlantic Aviation SGJ', 'Atlantic Aviation', 'Challenger 300', 1027, 404, 65, NULL, NULL, 'Complimentary (first hour) $30/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('SGJ', 'Atlantic Aviation SGJ', 'Atlantic Aviation', 'Citation X', 1086, 374, 65, NULL, NULL, 'Complimentary (first hour) $32/hr (next 11 hours) then $17/hr', 'jetinsight'),
  ('SGU', 'Million Air SGU', 'Million Air', 'Challenger 300', 569, 450, 62, 0, 0, '', 'jetinsight'),
  ('SGU', 'Million Air SGU', 'Million Air', 'Citation X', 400, 350, 39, 0, 0, '', 'jetinsight'),
  ('SGU', 'Sandstone Aviation SGU', 'Sandstone Aviation', 'Challenger 300', 75, 1, 0, 0, 0, '', 'jetinsight'),
  ('SGU', 'Sandstone Aviation SGU', 'Sandstone Aviation', 'Citation X', 75, 1, 0, 0, 0, '', 'jetinsight'),
  ('SHV', 'SIGNATURE SHREVEPORT', 'Signature Flight Support', 'Challenger 300', 1140, 520, 26, NULL, NULL, '', 'jetinsight'),
  ('SHV', 'SIGNATURE SHREVEPORT', 'Signature Flight Support', 'Citation X', 1140, 520, 26, NULL, NULL, '', 'jetinsight'),
  ('SJC', 'Atlantic Aviation SJC', 'Atlantic Aviation', 'Challenger 300', 1268, 404, 65, NULL, NULL, 'Complimentary (first hour) $29/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('SJC', 'Atlantic Aviation SJC', 'Atlantic Aviation', 'Citation X', 1341, 374, 65, NULL, NULL, 'Complimentary (first hour) $30/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('SJC', 'SIGNATURE SAN JOSE', 'Signature Flight Support', 'Citation X', 1660, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('SKB', 'SIGNATURE ST. KITTS', 'Signature Flight Support', 'Challenger 300', 1400, NULL, 40, NULL, NULL, '', 'jetinsight'),
  ('SKB', 'SIGNATURE ST. KITTS', 'Signature Flight Support', 'Citation X', 1400, NULL, 40, NULL, NULL, '', 'jetinsight'),
  ('SKF', 'Atlantic Aviation SKF', 'Atlantic Aviation', 'Challenger 300', 1049, 404, 55, NULL, NULL, '{''unitPrice'': 459.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('SKF', 'Atlantic Aviation SKF', 'Atlantic Aviation', 'Citation X', 1110, 374, 55, NULL, NULL, '{''unitPrice'': 485.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('SLC', 'Atlantic Aviation SLC', 'Atlantic Aviation', 'Challenger 300', 1180, 404, 55, NULL, NULL, 'Complimentary (first hour) $24/hr (next 11 hours) then $13/hr', 'jetinsight'),
  ('SLC', 'Atlantic Aviation SLC', 'Atlantic Aviation', 'Citation X', 1248, 374, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('SLC', 'SIGNATURE SALT LAKE CITY', 'Signature Flight Support', 'Challenger 300', 1510, 520, 27, NULL, NULL, '', 'jetinsight'),
  ('SLC', 'SIGNATURE SALT LAKE CITY', 'Signature Flight Support', 'Citation X', 1510, 520, 27, NULL, NULL, '', 'jetinsight'),
  ('SMF', 'Modern Aviation Sacramento', 'Modern Aviation', 'Challenger 300', 1700, 410, 60, 0, 403, '$403, 1 night / 0 gals', 'jetinsight'),
  ('SMF', 'Modern Aviation Sacramento', 'Modern Aviation', 'Citation X', 1700, 410, 60, 0, 403, '$403, 1 night / 0 gals', 'jetinsight'),
  ('SMO', 'Atlantic Aviation SMO', 'Atlantic Aviation', 'Challenger 300', 1224, 404, 65, NULL, NULL, 'Complimentary (first hour) $52/hr (next 11 hours) then $28/hr', 'jetinsight'),
  ('SMO', 'Atlantic Aviation SMO', 'Atlantic Aviation', 'Citation X', 1295, 374, 65, NULL, NULL, 'Complimentary (first hour) $55/hr (next 11 hours) then $30/hr', 'jetinsight'),
  ('SRQ', 'Atlantic Aviation SRQ', 'Atlantic Aviation', 'Challenger 300', 1180, 404, 65, NULL, NULL, '{''unitPrice'': 372.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('SRQ', 'Atlantic Aviation SRQ', 'Atlantic Aviation', 'Citation X', 1248, 374, 65, NULL, NULL, '{''unitPrice'': 393.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('STL', 'SIGNATURE ST. LOUIS', 'Signature Flight Support', 'Challenger 300', 2600, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('STL', 'SIGNATURE ST. LOUIS', 'Signature Flight Support', 'Citation X', 2600, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('STP', 'SIGNATURE ST. PAUL DOWNTOWN', 'Signature Flight Support', 'Challenger 300', 1720, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('STP', 'SIGNATURE ST. PAUL DOWNTOWN', 'Signature Flight Support', 'Citation X', 1720, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('STT', 'SIGNATURE ST. THOMAS', 'Signature Flight Support', 'Challenger 300', 1040, NULL, NULL, NULL, NULL, '', 'jetinsight'),
  ('STT', 'SIGNATURE ST. THOMAS', 'Signature Flight Support', 'Citation X', 1040, NULL, NULL, NULL, NULL, '', 'jetinsight'),
  ('SUA', 'Atlantic Aviation SUA', 'Atlantic Aviation', 'Challenger 300', 1049, 404, 55, NULL, NULL, 'Complimentary (first hour) $81/hr (next 11 hours) then $45/hr', 'jetinsight'),
  ('SUA', 'Atlantic Aviation SUA', 'Atlantic Aviation', 'Citation X', 1110, 374, 55, NULL, NULL, 'Complimentary (first hour) $87/hr (next 11 hours) then $45/hr', 'jetinsight'),
  ('SUN', 'Atlantic Aviation SUN', 'Atlantic Aviation', 'Challenger 300', 1180, 404, 85, NULL, NULL, '{''unitPrice'': 0.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('SUN', 'Atlantic Aviation SUN', 'Atlantic Aviation', 'Citation X', 1248, 374, 85, NULL, NULL, '{''unitPrice'': 0.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('SUS', 'Aero Charter Jet Center SUS', 'Aero Charter Jet Center', 'Challenger 300', 440, 350, 25, 0, 0, '', 'jetinsight'),
  ('SUS', 'Aero Charter Jet Center SUS', 'Aero Charter Jet Center', 'Citation X', 280, 225, 25, 0, 0, '', 'jetinsight'),
  ('SUS', 'Million Air SUS', 'Million Air', 'Challenger 300', 150, 1, 15, 0, 0, '', 'jetinsight'),
  ('SUS', 'Million Air SUS', 'Million Air', 'Citation X', 150, 1, 15, 0, 0, '', 'jetinsight'),
  ('SUS', 'SIGNATURE CHESTERFIELD', 'Signature Flight Support', 'Challenger 300', 2240, 520, 26, 0, 405, '', 'jetinsight'),
  ('SUS', 'SIGNATURE CHESTERFIELD', 'Signature Flight Support', 'Citation X', 2240, 520, 26, 0, 405, '', 'jetinsight'),
  ('SWF', 'Atlantic Aviation SWF', 'Atlantic Aviation', 'Challenger 300', 918, 404, 55, NULL, NULL, 'Complimentary (first hour) $29/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('SWF', 'Atlantic Aviation SWF', 'Atlantic Aviation', 'Citation X', 971, 374, 55, NULL, NULL, 'Complimentary (first hour) $30/hr (next 11 hours) then $16/hr', 'jetinsight'),
  ('SWF', 'SIGNATURE STEWART', 'Signature Flight Support', 'Challenger 300', 1510, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('SWF', 'SIGNATURE STEWART', 'Signature Flight Support', 'Citation X', 1510, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('SXM', 'SIGNATURE ST MAARTEN', 'Signature Flight Support', 'Challenger 300', 1378, NULL, 36.84, NULL, NULL, '', 'jetinsight'),
  ('SXM', 'SIGNATURE ST MAARTEN', 'Signature Flight Support', 'Citation X', 1378, NULL, 36.84, NULL, NULL, '', 'jetinsight'),
  ('TEB', 'Atlantic Aviation TEB', 'Atlantic Aviation', 'Challenger 300', 1224, 404, 235, 178, 1237, '$1,237, 0 night / 0% waived with 0 gals', 'jetinsight'),
  ('TEB', 'Atlantic Aviation TEB', 'Atlantic Aviation', 'Citation X', 1295, 374, 235, 0, 1305, '$1,305, 0 night / 0% waived with 0 gals', 'jetinsight'),
  ('TEB', 'Jet Aviation TEB', 'Jet Aviation', 'Challenger 300', 900, 450, 125, 178, 692, '$692, 0 night / 0% waived with 0 gals', 'jetinsight'),
  ('TEB', 'Jet Aviation TEB', 'Jet Aviation', 'Citation X', 900, 450, 125, 0, 692, '$692, 0 night / 0% waived with 0 gals', 'jetinsight'),
  ('TEB', 'SIGNATURE TETERBORO - TERMINAL EAST', 'Signature Flight Support', 'Challenger 300', 1980, 520, 73, 178, 1400, '', 'jetinsight'),
  ('TEB', 'SIGNATURE TETERBORO - TERMINAL SOUTH', 'Signature Flight Support', 'Challenger 300', 1980, 520, 73, 178, 1400, '', 'jetinsight'),
  ('TEB', 'SIGNATURE TETERBORO - TERMINAL WEST', 'Signature Flight Support', 'Challenger 300', 1980, 520, 73, 178, 1400, '', 'jetinsight'),
  ('TEB', 'SIGNATURE TETERBORO - TERMINAL EAST', 'Signature Flight Support', 'Citation X', 1980, 520, 73, 0, 1400, '', 'jetinsight'),
  ('TEB', 'SIGNATURE TETERBORO - TERMINAL SOUTH', 'Signature Flight Support', 'Citation X', 1980, 520, 73, 0, 1400, '', 'jetinsight'),
  ('TEB', 'SIGNATURE TETERBORO - TERMINAL WEST', 'Signature Flight Support', 'Citation X', 1980, 520, 73, 0, 1400, '', 'jetinsight'),
  ('TMB', 'SIGNATURE MIAMI EXECUTIVE', 'Signature Flight Support', 'Citation X', 1140, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('TPA', 'SIGNATURE TAMPA', 'Signature Flight Support', 'Citation X', 1200, 520, 36, NULL, NULL, '', 'jetinsight'),
  ('TRM', 'Atlantic Aviation TRM', 'Atlantic Aviation', 'Challenger 300', 1180, 404, 55, NULL, NULL, '{''unitPrice'': 393.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('TRM', 'Atlantic Aviation TRM', 'Atlantic Aviation', 'Citation X', 1248, 374, 55, NULL, NULL, '{''unitPrice'': 416.0, ''comment'': ''Parking/Tie Down''}', 'jetinsight'),
  ('TTN', 'SIGNATURE TRENTON', 'Signature Flight Support', 'Citation X', 1460, 520, 47, NULL, NULL, '', 'jetinsight'),
  ('TUL', 'Atlantic Aviation TUL', 'Atlantic Aviation', 'Challenger 300', 1137, 404, 55, NULL, NULL, 'Complimentary (first hour) $24/hr (next 11 hours) then $13/hr', 'jetinsight'),
  ('TUL', 'Atlantic Aviation TUL', 'Atlantic Aviation', 'Citation X', 1202, 374, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('TUS', 'Atlantic Aviation TUS', 'Atlantic Aviation', 'Challenger 300', 1159, 404, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('TUS', 'Atlantic Aviation TUS', 'Atlantic Aviation', 'Citation X', 1225, 374, 55, NULL, NULL, 'Complimentary (first hour) $27/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('TXK', 'SIGNATURE TEXARKANA', 'Signature Flight Support', 'Challenger 300', 990, 520, 26, NULL, NULL, '', 'jetinsight'),
  ('TXK', 'SIGNATURE TEXARKANA', 'Signature Flight Support', 'Citation X', 990, 520, 26, NULL, NULL, '', 'jetinsight'),
  ('TYS', 'SIGNATURE KNOXVILLE', 'Signature Flight Support', 'Challenger 300', 1720, 520, 32, NULL, NULL, '', 'jetinsight'),
  ('TYS', 'SIGNATURE KNOXVILLE', 'Signature Flight Support', 'Citation X', 1720, 520, 32, NULL, NULL, '', 'jetinsight'),
  ('UAO', 'Atlantic Aviation UAO', 'Atlantic Aviation', 'Challenger 300', 1027, 404, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('UAO', 'Atlantic Aviation UAO', 'Atlantic Aviation', 'Citation X', 1086, 374, 55, NULL, NULL, 'Complimentary (first hour) $27/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('UES', 'Atlantic Aviation UES', 'Atlantic Aviation', 'Challenger 300', 918, 404, 55, NULL, NULL, 'Complimentary (first hour) $25/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('UES', 'Atlantic Aviation UES', 'Atlantic Aviation', 'Citation X', 971, 374, 55, NULL, NULL, 'Complimentary (first hour) $27/hr (next 11 hours) then $14/hr', 'jetinsight'),
  ('UGN', 'SIGNATURE WAUKEGAN', 'Signature Flight Support', 'Citation X', 2030, 520, 38, NULL, NULL, '', 'jetinsight'),
  ('UVF', 'SIGNATURE ST. LUCIA', 'Signature Flight Support', 'Challenger 300', 1510, NULL, 350, NULL, NULL, '', 'jetinsight'),
  ('UVF', 'SIGNATURE ST. LUCIA', 'Signature Flight Support', 'Citation X', 1510, NULL, 350, NULL, NULL, '', 'jetinsight'),
  ('VNY', 'Castle & Cooke Aviation VNY', 'Castle & Cooke Aviation', 'Challenger 300', 1000, 600, 25, 217, 800, '$800, 1 night / 450 gals', 'jetinsight'),
  ('VNY', 'Castle & Cooke Aviation VNY', 'Castle & Cooke Aviation', 'Citation X', 825, 450, 25, 0, 800, '$800, 1 night / 450 gals', 'jetinsight'),
  ('VNY', 'Clay Lacy Aviation VNY', 'Clay Lacy Aviation', 'Challenger 300', 650, 800, 65, 217, 650, '', 'jetinsight'),
  ('VNY', 'Clay Lacy Aviation VNY', 'Clay Lacy Aviation', 'Citation X', 650, 800, 65, 0, 650, '', 'jetinsight'),
  ('VNY', 'Van Nuys, USA', 'Jet Aviation', 'Challenger 300', 750, 450, 45, 217, 508, '', 'jetinsight'),
  ('VNY', 'Van Nuys, USA', 'Jet Aviation', 'Citation X', 750, 450, 45, 0, 508, '', 'jetinsight'),
  ('VNY', 'Signature Van Nuys – East', 'Signature Flight Support', 'Challenger 300', 2340, 520, 43, 217, 715, '', 'jetinsight'),
  ('VNY', 'Signature Van Nuys – West', 'Signature Flight Support', 'Challenger 300', 2340, 520, 43, 217, 715, '', 'jetinsight'),
  ('VNY', 'Signature Van Nuys – East', 'Signature Flight Support', 'Citation X', 2340, 520, 43, 0, 715, '', 'jetinsight'),
  ('VNY', 'Signature Van Nuys – West', 'Signature Flight Support', 'Citation X', 2340, 520, 43, 0, 715, '', 'jetinsight')
ON CONFLICT (airport_code, fbo_name, aircraft_type) DO UPDATE SET
  chain = EXCLUDED.chain, facility_fee = EXCLUDED.facility_fee, gallons_to_waive = EXCLUDED.gallons_to_waive,
  security_fee = EXCLUDED.security_fee, landing_fee = EXCLUDED.landing_fee, overnight_fee = EXCLUDED.overnight_fee,
  parking_info = EXCLUDED.parking_info, source = EXCLUDED.source, updated_at = now();
